### ISSUE TITLE
Faiwuwe to woad wibvulkan.so does nyot fawwback to wibvulkan.so.1. (´ヘ｀()

### ISSUE THREAD

**Issue by TreePuncher** [enlynn/vtuber_renderer#3]
OwO, On some distwos wibvulkan.so is pwovided in vulkan-woadew-devew instead of packaged by defauwt. It's nyot fawwing back to woading wibvulkan.so.1. The cwass WibwawyDLL shouwd pwobabwy handwe fawwing back fow winux buiwds.

**Comment by enlynn** [comment]
0c6565f1282eebc2413dbf8397aad603b06e1fcc
